title: Adani Blogs
author: Afdul Anwar Adani
description: >-
  Adani | Blog : afdulanwaradani.github.io merupakan blog yang Adani buat dari
  github pages dimana akan memberikan informasi menarik seperti blog, SEO,
  Website, Blogger, Backlin dan Tips Trik.
permalink: '/:title/'
lang: id
excerpt_separator: |+



date_format: '%B %d, %Y'
show_excerpts: true
show_frame: true
show_sidebar: false
minimal: false
navigation:
  - file: index.html
  - file: README.md
external:
  - title: Mail
    icon: envelope
    url: 'mailto:afdulanwaradani@users.noreply.github.com'
  - title: Github
    icon: github
    url: 'https://github.com/afdulanwaradani'
  - title: Subscribe
    icon: rss
    url: /feed.xml
comments: null
plugins:
  - jekyll-feed
